version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  app:
    build: .
    container_name: expensify-integration
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/vendorExpense
      - EXPENSIFY_CLIENT_ID=${EXPENSIFY_CLIENT_ID}
      - EXPENSIFY_CLIENT_SECRET=${EXPENSIFY_CLIENT_SECRET}
    depends_on:
      - mongodb

volumes:
  mongodb_data: